### ISSUE TITLE
Error sending message: Error: Header image must not have a caption

### ISSUE THREAD

**Issue by HysMX** [Secreto31126/whatsapp-api-js#198]
**Describe the bug**
An error in console while trying to send a broadcast message 

**To Reproduce**
```ts
const image = new Image("https://i.imgur.com/RZ1MmvC.png")
const button = new Interactive(
  new ActionButtons(
    new Button("button_quote_offer", "Responder"),
    new Button("button_quote_ignore", "Ignorar")
  ),
  new Body(`*Nueva Solicitud*
*Cliente:* ${customer?.name}
*Solicitud:* ${prompt}
*Producto / Servicio:*: ${product}
*Categoría:* ${category}
*Presupuesto:* ${price}
  `),
  new Header(image)
);
      
const responses = await Whatsapp.broadcastMessage(PHONE_ID, recipients, button);

Promise.all(responses).then(console.log);    
```

**Expected behavior**
Send the message with the image header

It was sending the message just fine until i updated the library to the latest version, the code is unmodified

**Comment by HysMX** [comment]
Downgraded to 1.0.2 and worked just fine
![image](https://github.com/Secreto31126/whatsapp-api-js/assets/50180189/de6e67c5-f8f3-4b8a-8cfd-4998a53aace8)

**Comment by Secreto31126** [comment]
This is a really weird issue. The diff between 1.0.2..1.0.3 only includes changes for template.ts, so your code shouldn't be affected by the update...

I will test your code in a few hours and try to find the solution.

Thanks!

**Comment by Secreto31126** [comment]
I managed to replicate the issue, and to my surprise it's REALLY weird.

Given this snippet:

```typescript
const image = new Image("https://i.imgur.com/RZ1MmvC.png");
console.log(image);
```

The obtained output on 1.0.2 is:

```typescript
{ link: 'https://i.imgur.com/RZ1MmvC.png' }
```

However, on 1.0.3 (and v2), the terminal logs the following:

```typescript
{
  id: undefined,
  link: 'https://i.imgur.com/RZ1MmvC.png',
  caption: undefined
}
```

Which is really annoying, because the library uses the keyword `in` to check if the class contains such property. Although undefined, the property is in the object, hence throwing the error as it thinks the image contains a caption.

My only guess for this issue is a breaking dev dependecy update. I will try to find out which one and see if it's intentional or not. IIRC, esbuild had a mid version update, so maybe the issue is there.

This is why people write unit tests :)

Thanks for opening the issue.

**Comment by Secreto31126** [comment]
Hi, I just published 1.0.4 to npm with a bug fix.Let me know if it works!

**Comment by HysMX** [comment]
The error persists on 1.0.4 its weird because logging the image object only returns the URL
![image](https://github.com/Secreto31126/whatsapp-api-js/assets/50180189/fc7ee4e8-755f-4367-a0f1-33892e1541d7)

Image Object 
![image](https://github.com/Secreto31126/whatsapp-api-js/assets/50180189/52ffc187-3031-4540-b3d8-04694634e0c5)

Code:
```js
        const image = new Image("https://i.imgur.com/CFpN5kh.png");
        console.log(JSON.stringify(image), "imagen 2")
        const button = new Interactive(
          new ActionButtons(
            new Button("button_menu_seller", "Vendedor"),
            new Button("button_menu_buyer", "Comprador")
          ),
          new Body(`¡Bienvenido de nuevo ${customer.name}! ¿Qué menu deseas visualizar?`),
          new Header(image)
        );
        await Whatsapp.sendMessage(PHONE_ID as string,message.from, button);
```

**Comment by Secreto31126** [comment]
That's unfortunate. Seems like a full update will be necessary. I will do it later today.

**Comment by HysMX** [comment]
Thank you, pibe, where can i send you a tip? 😋 con eso de que el dólar está por las nubes en argentina

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Tomás Raiti ***@***.***>
Enviado: Thursday, August 24, 2023 3:57:16 AM
Para: Secreto31126/whatsapp-api-js ***@***.***>
Cc: Omar ***@***.***>; Author ***@***.***>
Asunto: Re: [Secreto31126/whatsapp-api-js] Error sending message: Error: Header image must not have a caption (Issue #198)


That's unfortunate. Seems like a full update will be necessary. I will do it later today.

**Comment by Secreto31126** [comment]
Wow, eso sería increíble. Si realmente creés que vale la pena, podés usar Patreon:

[https://patreon.com/Secreto31126](https://patreon.com/Secreto31126)

Muchísimas gracias 😁.

(Sí, el dólar es un caos acá 😂)

**Comment by Secreto31126** [comment]
I just did a full rewrite of the property checks and published to the beta tag, let me know if it fixes it for you!

**Comment by Secreto31126** [comment]
Based on my white box tests I believe the issue is fixed, so I will publish to npm and close the issue.

Thanks for reporting!
